apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: viral-clip-ai
  labels:
    app.kubernetes.io/name: otel-collector
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        loglevel: info
      prometheus:
        endpoint: 0.0.0.0:9464
      otlphttp:
        endpoint: https://otlp.example.com
        headers:
          Authorization: Bearer example-token
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: viral-clip-ai
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.92.0
          args: ["--config=/etc/otel/collector.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/otel
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 9464
              name: metrics
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
            items:
              - key: collector.yaml
                path: collector.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: viral-clip-ai
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  ports:
    - port: 4317
      targetPort: otlp-grpc
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      name: otlp-http
    - port: 9464
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: otel-collector
