apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  namespace: viral-clip-ai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ui-pdb
  namespace: viral-clip-ai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workers-pdb
  namespace: viral-clip-ai
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workers